"use client";
import localFont from "next/font/local";
import { Providers as AntProvider } from "./provider";

import "./globals.css";
import Footer from "@/components/templates/Footer/Footer";
import Header from "@/components/templates/Headers/Header";
import { UserProvider } from "@/context/UserContext";
import { ProductProvider } from "@/context/ProductContext";
import { ToastContainer } from "react-toastify";
import { BlogProvider } from "@/context/BlogContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntProvider>
          <ToastContainer position="top-right" />
          <UserProvider>
            <ProductProvider>
              <BlogProvider>
                <Header />
                {children}
                <Footer />
              </BlogProvider>
            </ProductProvider>
          </UserProvider>
        </AntProvider>
      </body>
    </html>
  );
}
